apiVersion: apps/v1
kind: Deployment
metadata:
  name: drupal
  labels:
    app: drupal
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "drupal.selectorLabels" . | nindent 6 }}
      app: drupal
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "drupal.selectorLabels" . | nindent 8 }}
        app: {{ .Values.images.drupal.name }}
        version: {{ .Values.appVersion }}
    spec:
      imagePullSecrets:
        - name: quant-cloud
      volumes:
        - name: drupal-data
          persistentVolumeClaim:
            claimName: drupal-pvc
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        ### BEGIN DRUPAL CONTAINER
        - name: {{ .Values.images.drupal.name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.images.drupal.repository }}:{{ .Values.images.drupal.tag }}"
          imagePullPolicy: {{ .Values.images.drupal.pullPolicy | default .Values.images.pullPolicy }}
          ports:
            - name: {{ .Values.images.drupal.name }}
              containerPort: {{ .Values.images.drupal.port }}
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 2
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: {{ .Values.images.drupal.port }}
            timeoutSeconds: 1
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 2
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: {{ .Values.images.drupal.port }}
            timeoutSeconds: 1
          envFrom:
            - configMapRef:
                name: drupal-config
          volumeMounts:
            - name: drupal-data
              mountPath: /opt/drupal/web/sites/default/files

          resources:
            {{- toYaml .Values.images.drupal.resources | nindent 12 }}
        ### END DRUPAL CONTAINER

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}