# This is a YAML-formatted file.
# Provides default variables to be passed into your templates.

replicaCount: 2

nameOverride: ""
fullnameOverride: ""

images:
  pullPolicy: Always
  drupal:
    name: drupal
    repository: registry.quant.cloud/org/repo
    tag: edge
    port: 80
    resources:
      limits:
        cpu: 1000m
        memory: 1024Mi
      requests:
        cpu: 1000m
        memory: 1024Mi

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  name: drupal
  type: ClusterIP
  port: 80

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# Use this for local deployments only.
# KEI ingress is managed separately.
ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "0.1.0"

# Secrets
# Manage app secrets with kubernetes rather than committing
# in the codebase itself.
secrets:
  registry:
    user:
    token:
    registry: registry.quant.cloud
  database:
    username:
    password:
    database:
    host: example.rds.amazonaws.com
    port: 3306