tasks:
  - name: Build Application
    before: |
      ddev config global --instrumentation-opt-in=true
    init: |
      ddev start -y
      ddev composer install
    command: gp sync-done build_application
  - name: Open Browser
    command: |
      gp sync-await build_application
      ddev start -y
      ddev drush cr
      gp preview $(gp url 8080)
      ddev drush uli
# VScode extensions
vscode:
  extensions:
    # Twig language support
    - mblode.twig-language-2
    # YAML language support
    - redhat.vscode-yaml
    # PHP documentation block support
    - neilbrayfield.php-docblocker
    # PHP code intelligence
    - bmewburn.vscode-intelephense-client
    # Gherkin support for Behat test writing
    - alexkrechik.cucumberautocomplete
    # Drupal API support
    - andrewdavidblum.drupal-smart-snippets
    # Git Extension Pack including Git Lens
    - donjayamanne.git-extension-pack
ports:
  # Used by ddev - local db clients
  - port: 3306
    onOpen: ignore
  # Used by MailHog
  - port: 8027
    onOpen: ignore
 # Used by phpMyAdmin
  - port: 8036
    onOpen: ignore
  # Direct-connect ddev-webserver port that is the main port
  - port: 8080
    onOpen: ignore
    visibility: public
  # Ignore host https port
  - port: 8443
    onOpen: ignore
 # xdebug port
  - port: 9003
    onOpen: ignore
