apiVersion: v1
kind: ConfigMap
metadata:
  name: drupal-config
data:
    MARIADB_USER: ${MARIADB_USER}
    MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    MARIADB_DATABASE: ${MARIADB_DATABASE}
    MARIADB_HOST: ${MARIADB_HOST}
    MARIADB_PORT: ${MARIADB_PORT}
    MARIADB_PREFIX: ${MARIADB_PREFIX}
