apiVersion: apps/v1
kind: Deployment
metadata:
  name: drupal
  labels:
    app: drupal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drupal
  template:
    metadata:
      labels:
        app: drupal
    spec:
      containers:
      - name: drupal
        image: ${IMAGE_NAME}:${IMAGE_TAG}
        imagePullPolicy: Always
        envFrom:
            - configMapRef:
                name: drupal-config
        volumeMounts:
          - name: drupal-data
            mountPath: /opt/drupal/web/sites/default/files
        resources:
          requests:
            memory: "200Mi"
            cpu: "200m"
          limits:
            memory: "1024Mi"
            cpu: "1000m"
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: quant-cloud
      volumes:
        - name: drupal-data
          persistentVolumeClaim:
            claimName: drupal-pvc