apiVersion: v1
kind: Service
metadata:
  name: ingress-upstream
  namespace: default
  labels:
    app: ingress-upstream
spec:
    ports:
    - name: 80-{{ .Values.images.drupal.port }}
      port: 80
      protocol: TCP
      targetPort: {{ .Values.images.drupal.port }}
    selector:
        app: drupal
    sessionAffinity: None
    type: ClusterIP
status:
    loadBalancer: {}