name: Schedule tasks

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */3 * * *"

jobs:
  scheduled_tasks:
    runs-on: ubuntu-latest
    steps:
      - name: Setup kubeconfig
        env:
          SECTION_K8S_API_URL: "${{ secrets.SECTION_K8S_API_URL }}"
          SECTION_API_TOKEN: "${{ secrets.SECTION_API_TOKEN }}"
        run: |
          ./ci/init-kube.sh
          echo 'KUBECONFIG<<EOF' >> $GITHUB_ENV
          echo $(cat ~/.kube/config | base64) >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

      - uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ env.KUBECONFIG }}
        with:
          args: exec deploy/drupal -- drush status